(function () {
    const CLASSIFICATION_LEVELS = {
        easy: {
            title: "陸地動物 vs 海洋動物",
            categories: ["陸地動物", "海洋動物"],
            items: [
                {
                    id: "animal-dolphin",
                    label: "海豚",
                    image: "/static/images/games/classify/easy/animal_0008.png",
                    category: "海洋動物",
                },
                {
                    id: "animal-eagle",
                    label: "老鷹",
                    image: "/static/images/games/classify/easy/animal_0009.png",
                    category: "鳥類",
                },
                {
                    id: "animal-falcon",
                    label: "獵鷹",
                    image: "/static/images/games/classify/easy/animal_0010.png",
                    category: "鳥類",
                },
                {
                    id: "animal-mouse",
                    label: "老鼠",
                    image: "/static/images/games/classify/easy/animal_0011.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-flamingo",
                    label: "紅鶴",
                    image: "/static/images/games/classify/easy/animal_0012.png",
                    category: "鳥類",
                },
                {
                    id: "animal-fox",
                    label: "狐狸",
                    image: "/static/images/games/classify/easy/animal_0013.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-goose",
                    label: "鵝",
                    image: "/static/images/games/classify/easy/animal_0014.png",
                    category: "鳥類",
                },
                {
                    id: "animal-gorilla",
                    label: "大猩猩",
                    image: "/static/images/games/classify/easy/animal_0015.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-guinea-pig",
                    label: "天竺鼠",
                    image: "/static/images/games/classify/easy/animal_0016.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-hamster",
                    label: "倉鼠",
                    image: "/static/images/games/classify/easy/animal_0017.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-hedgehog",
                    label: "刺蝟",
                    image: "/static/images/games/classify/easy/animal_0018.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-hummingbird",
                    label: "蜂鳥",
                    image: "/static/images/games/classify/easy/animal_0019.png",
                    category: "鳥類",
                },
                {
                    id: "animal-jellyfish",
                    label: "水母",
                    image: "/static/images/games/classify/easy/animal_0020.png",
                    category: "海洋動物",
                },
                {
                    id: "animal-ferret",
                    label: "雪貂",
                    image: "/static/images/games/classify/easy/animal_0001.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-llama",
                    label: "羊駝",
                    image: "/static/images/games/classify/easy/animal_0002.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-bear",
                    label: "熊",
                    image: "/static/images/games/classify/easy/animal_0003.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-bull",
                    label: "公牛",
                    image: "/static/images/games/classify/easy/animal_0004.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-camel",
                    label: "駱駝",
                    image: "/static/images/games/classify/easy/animal_0005.png",
                    category: "陸地動物",
                },
                {
                    id: "animal-clownfish",
                    label: "小丑魚",
                    image: "/static/images/games/classify/easy/animal_0006.png",
                    category: "海洋動物",
                },
                {
                    id: "animal-crab",
                    label: "螃蟹",
                    image: "/static/images/games/classify/easy/animal_0007.png",
                    category: "海洋動物",
                },
            ],
        },
        medium: {
            title: "水果 vs 蔬菜 vs 麵包",
            categories: ["水果", "蔬菜", "麵包"],
            items: [
                {
                    id: "medium-peach",
                    label: "桃子",
                    image: "/static/images/games/classify/medium/food_0001.png",
                    category: "水果",
                },
                {
                    id: "medium-lettuce",
                    label: "萵苣",
                    image: "/static/images/games/classify/medium/food_0002.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-broccoli",
                    label: "花椰菜",
                    image: "/static/images/games/classify/medium/food_0003.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-bell-pepper",
                    label: "甜椒",
                    image: "/static/images/games/classify/medium/food_0004.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-cucumber",
                    label: "小黃瓜",
                    image: "/static/images/games/classify/medium/food_0006.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-peas",
                    label: "豌豆",
                    image: "/static/images/games/classify/medium/food_0009.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-kiwi",
                    label: "奇異果",
                    image: "/static/images/games/classify/medium/food_0010.png",
                    category: "水果",
                },
                {
                    id: "medium-apple",
                    label: "蘋果",
                    image: "/static/images/games/classify/medium/food_0012.png",
                    category: "水果",
                },
                {
                    id: "medium-banana",
                    label: "香蕉",
                    image: "/static/images/games/classify/medium/food_0018.png",
                    category: "水果",
                },
                {
                    id: "medium-bread",
                    label: "吐司",
                    image: "/static/images/games/classify/medium/food_0021.png",
                    category: "麵包",
                },
                {
                    id: "medium-baguette",
                    label: "法國麵包",
                    image: "/static/images/games/classify/medium/food_0022.png",
                    category: "麵包",
                },
                {
                    id: "medium-mooncake",
                    label: "月餅",
                    image: "/static/images/games/classify/medium/food_0026.png",
                    category: "麵包",
                },
                {
                    id: "medium-olive",
                    label: "橄欖",
                    image: "/static/images/games/classify/medium/food_0027.png",
                    category: "水果",
                },
                {
                    id: "medium-pear",
                    label: "梨子",
                    image: "/static/images/games/classify/medium/food_0028.png",
                    category: "水果",
                },
                {
                    id: "medium-pineapple",
                    label: "鳳梨",
                    image: "/static/images/games/classify/medium/food_0029.png",
                    category: "水果",
                },
                {
                    id: "medium-corn",
                    label: "玉米",
                    image: "/static/images/games/classify/medium/food_0031.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-grapes",
                    label: "葡萄",
                    image: "/static/images/games/classify/medium/food_0032.png",
                    category: "水果",
                },
                {
                    id: "medium-mango",
                    label: "芒果",
                    image: "/static/images/games/classify/medium/food_0033.png",
                    category: "水果",
                },
                {
                    id: "medium-strawberry",
                    label: "草莓",
                    image: "/static/images/games/classify/medium/food_0034.png",
                    category: "水果",
                },
                {
                    id: "medium-lemon",
                    label: "檸檬",
                    image: "/static/images/games/classify/medium/food_0035.png",
                    category: "水果",
                },
                {
                    id: "medium-apple-red",
                    label: "蘋果",
                    image: "/static/images/games/classify/medium/food_0051.png",
                    category: "水果",
                },
                {
                    id: "medium-watermelon",
                    label: "西瓜",
                    image: "/static/images/games/classify/medium/food_0052.png",
                    category: "水果",
                },
                {
                    id: "medium-blueberry",
                    label: "藍莓",
                    image: "/static/images/games/classify/medium/food_0053.png",
                    category: "水果",
                },
                {
                    id: "medium-cherry",
                    label: "櫻桃",
                    image: "/static/images/games/classify/medium/food_0054.png",
                    category: "水果",
                },
                {
                    id: "medium-eggplant",
                    label: "茄子",
                    image: "/static/images/games/classify/medium/food_0056.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-orange",
                    label: "柳橙",
                    image: "/static/images/games/classify/medium/food_0057.png",
                    category: "水果",
                },
                {
                    id: "medium-tomato",
                    label: "番茄",
                    image: "/static/images/games/classify/medium/food_0058.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-potato",
                    label: "馬鈴薯",
                    image: "/static/images/games/classify/medium/food_0059.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-carrot",
                    label: "紅蘿蔔",
                    image: "/static/images/games/classify/medium/food_0060.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-sweet-potato",
                    label: "地瓜",
                    image: "/static/images/games/classify/medium/food_0062.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-peanut",
                    label: "花生",
                    image: "/static/images/games/classify/medium/food_0063.png",
                    category: "蔬菜",
                },
                {
                    id: "medium-butter",
                    label: "奶油",
                    image: "/static/images/games/classify/medium/food_0075.png",
                    category: "麵包",
                },
                {
                    id: "medium-avocado",
                    label: "酪梨",
                    image: "/static/images/games/classify/medium/food_0077.png",
                    category: "水果",
                },
            ],
        },
        hard: {
            title: "衣服 vs 帽子 vs 鞋類 vs 眼鏡",
            categories: ["衣服", "帽子", "鞋類", "眼鏡"],
            items: [
                {
                    id: "hard-glasses-angular-brown",
                    label: "眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0008.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-glasses-round-brown",
                    label: "眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0001.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-sunglasses-brown",
                    label: "太陽眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0002.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-glasses-round-orange",
                    label: "眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0003.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-cat-eye-glasses",
                    label: "貓眼眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0004.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-browline-glasses",
                    label: "半框眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0005.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-rect-brown-glasses",
                    label: "眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0006.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-round-pink-glasses",
                    label: "眼鏡",
                    image: "/static/images/games/classify/hard/glasses_0007.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-flat-cap-gray",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0016.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-bowler-blue",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0001.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-cloche-red",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0002.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-top-black",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0003.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-sun-pink",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0004.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-bowler-brown",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0005.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-cowboy-gray",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0006.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-cowboy-brown",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0007.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-sun-cream",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0008.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-cowboy-tan",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0009.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-beret-blue",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0010.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-wide-brim-brown",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0011.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-fedora-dark",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0012.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-beret-orange",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0013.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-wide-brim-purple",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0014.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-straw-beige",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0015.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-cloche-purple",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0018.jpg",
                    category: "帽子",
                },
                {
                    id: "hard-hat-bowler-gray",
                    label: "帽子",
                    image: "/static/images/games/classify/hard/hats_0017.jpg",
                    category: "帽子",
                },
            ],
        },
    };

    window.CLASSIFICATION_LEVELS = CLASSIFICATION_LEVELS;
})();
