(function () {
  const classifyImage = (path) => `/static/images/games/classify/${path}`;

  const CLASSIFICATION_LEVELS = {
    easy: {
      title: "動物生活環境分類",
      categories: ["陸地動物", "水中動物", "鳥類"],
      items: [
        { id: "animal-ferret", label: "雪貂", image: classifyImage("easy/animal_0001.png"), category: "陸地動物" },
        { id: "animal-llama", label: "羊駝", image: classifyImage("easy/animal_0002.png"), category: "陸地動物" },
        { id: "animal-bear", label: "熊", image: classifyImage("easy/animal_0003.png"), category: "陸地動物" },
        { id: "animal-bull", label: "牛", image: classifyImage("easy/animal_0004.png"), category: "陸地動物" },
        { id: "animal-camel", label: "駱駝", image: classifyImage("easy/animal_0005.png"), category: "陸地動物" },
        { id: "animal-mouse", label: "老鼠", image: classifyImage("easy/animal_0011.png"), category: "陸地動物" },
        { id: "animal-fox", label: "狐狸", image: classifyImage("easy/animal_0013.png"), category: "陸地動物" },
        { id: "animal-gorilla", label: "大猩猩", image: classifyImage("easy/animal_0015.png"), category: "陸地動物" },
        { id: "animal-clownfish", label: "小丑魚", image: classifyImage("easy/animal_0006.png"), category: "水中動物" },
        { id: "animal-dolphin", label: "海豚", image: classifyImage("easy/animal_0008.png"), category: "水中動物" },
        { id: "animal-jellyfish", label: "水母", image: classifyImage("easy/animal_0020.png"), category: "水中動物" },
        { id: "animal-eagle", label: "老鷹", image: classifyImage("easy/animal_0009.png"), category: "鳥類" },
        { id: "animal-falcon", label: "獵鷹", image: classifyImage("easy/animal_0010.png"), category: "鳥類" },
        { id: "animal-flamingo", label: "火鶴", image: classifyImage("easy/animal_0012.png"), category: "鳥類" },
        { id: "animal-goose", label: "鵝", image: classifyImage("easy/animal_0014.png"), category: "鳥類" },
        { id: "animal-hummingbird", label: "蜂鳥", image: classifyImage("easy/animal_0019.png"), category: "鳥類" },
      ],
    },
    medium: {
      title: "日常用品分類",
      categories: ["衣服", "眼鏡", "帽子", "鞋子"],
      items: [
        { id: "clothe-1", label: "上衣", image: classifyImage("hard/clothe_0001.jpg"), category: "衣服" },
        { id: "clothe-2", label: "衣服", image: classifyImage("hard/clothe_0002.jpg"), category: "衣服" },
        { id: "clothe-3", label: "外套", image: classifyImage("hard/clothe_0003.jpg"), category: "衣服" },
        { id: "clothe-4", label: "襯衫", image: classifyImage("hard/clothe_0004.jpg"), category: "衣服" },
        { id: "glasses-1", label: "眼鏡", image: classifyImage("hard/glasses_0001.jpg"), category: "眼鏡" },
        { id: "glasses-2", label: "眼鏡", image: classifyImage("hard/glasses_0002.jpg"), category: "眼鏡" },
        { id: "glasses-3", label: "眼鏡", image: classifyImage("hard/glasses_0003.jpg"), category: "眼鏡" },
        { id: "glasses-4", label: "眼鏡", image: classifyImage("hard/glasses_0004.jpg"), category: "眼鏡" },
        { id: "hat-1", label: "帽子", image: classifyImage("hard/hats_0001.jpg"), category: "帽子" },
        { id: "hat-2", label: "帽子", image: classifyImage("hard/hats_0002.jpg"), category: "帽子" },
        { id: "hat-3", label: "帽子", image: classifyImage("hard/hats_0003.jpg"), category: "帽子" },
        { id: "hat-4", label: "帽子", image: classifyImage("hard/hats_0004.jpg"), category: "帽子" },
        { id: "shoe-1", label: "鞋子", image: classifyImage("hard/shoe_0001.jpg"), category: "鞋子" },
        { id: "shoe-2", label: "鞋子", image: classifyImage("hard/shoe_0002.jpg"), category: "鞋子" },
        { id: "shoe-3", label: "鞋子", image: classifyImage("hard/shoe_0003.jpg"), category: "鞋子" },
        { id: "shoe-4", label: "鞋子", image: classifyImage("hard/shoe_0004.jpg"), category: "鞋子" },
      ],
    },
    hard: {
      title: "日常用品進階分類",
      categories: ["衣服", "眼鏡", "帽子", "鞋子"],
      items: [
        { id: "clothe-1h", label: "上衣", image: classifyImage("hard/clothe_0001.jpg"), category: "衣服" },
        { id: "clothe-2h", label: "衣服", image: classifyImage("hard/clothe_0002.jpg"), category: "衣服" },
        { id: "clothe-3h", label: "外套", image: classifyImage("hard/clothe_0003.jpg"), category: "衣服" },
        { id: "clothe-4h", label: "襯衫", image: classifyImage("hard/clothe_0004.jpg"), category: "衣服" },
        { id: "clothe-5h", label: "衣服", image: classifyImage("hard/clothe_0005.jpg"), category: "衣服" },
        { id: "clothe-6h", label: "衣服", image: classifyImage("hard/clothe_0006.jpg"), category: "衣服" },
        { id: "glasses-1h", label: "眼鏡", image: classifyImage("hard/glasses_0001.jpg"), category: "眼鏡" },
        { id: "glasses-2h", label: "眼鏡", image: classifyImage("hard/glasses_0002.jpg"), category: "眼鏡" },
        { id: "glasses-3h", label: "眼鏡", image: classifyImage("hard/glasses_0003.jpg"), category: "眼鏡" },
        { id: "glasses-4h", label: "眼鏡", image: classifyImage("hard/glasses_0004.jpg"), category: "眼鏡" },
        { id: "glasses-5h", label: "眼鏡", image: classifyImage("hard/glasses_0005.jpg"), category: "眼鏡" },
        { id: "glasses-6h", label: "眼鏡", image: classifyImage("hard/glasses_0006.jpg"), category: "眼鏡" },
        { id: "hat-1h", label: "帽子", image: classifyImage("hard/hats_0001.jpg"), category: "帽子" },
        { id: "hat-2h", label: "帽子", image: classifyImage("hard/hats_0002.jpg"), category: "帽子" },
        { id: "hat-3h", label: "帽子", image: classifyImage("hard/hats_0003.jpg"), category: "帽子" },
        { id: "hat-4h", label: "帽子", image: classifyImage("hard/hats_0004.jpg"), category: "帽子" },
        { id: "hat-5h", label: "帽子", image: classifyImage("hard/hats_0005.jpg"), category: "帽子" },
        { id: "hat-6h", label: "帽子", image: classifyImage("hard/hats_0006.jpg"), category: "帽子" },
        { id: "shoe-1h", label: "鞋子", image: classifyImage("hard/shoe_0001.jpg"), category: "鞋子" },
        { id: "shoe-2h", label: "鞋子", image: classifyImage("hard/shoe_0002.jpg"), category: "鞋子" },
        { id: "shoe-3h", label: "鞋子", image: classifyImage("hard/shoe_0003.jpg"), category: "鞋子" },
        { id: "shoe-4h", label: "鞋子", image: classifyImage("hard/shoe_0004.jpg"), category: "鞋子" },
        { id: "shoe-5h", label: "鞋子", image: classifyImage("hard/shoe_0005.jpg"), category: "鞋子" },
        { id: "shoe-6h", label: "鞋子", image: classifyImage("hard/shoe_0006.jpg"), category: "鞋子" },
      ],
    },
  };

  window.CLASSIFICATION_LEVELS = CLASSIFICATION_LEVELS;
})();
